#!/usr/bin/env python3
#
#  Copyright 2010-2016 Peter Williams <pwil3058@gmail.com>
#
# This software is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License only.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this software; if not, write to:
#  The Free Software Foundation, Inc., 51 Franklin Street,
#  Fifth Floor, Boston, MA 02110-1301 USA

'''GUI interface for the darning patch management system'''

__author__ = "Peter Williams <pwil3058@gmail.com>"

import argparse
import os
import sys

import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

from darning.gtx import recollect
from darning.gtx import dialogue
from darning.gui import main_window

parser = argparse.ArgumentParser(description=_('GUI to manage stacked patches'))

parser.add_argument(
    'playground',
    help=_('Directory where patches are to be managed'),
    metavar=_('dir'),
    nargs='?'
)

args = parser.parse_args()

# TODO: rationalize and simplify "gdarn" start up

if args.playground:
    try:
        os.chdir(args.playground)
    except OSError as msg:
        sys.stderr.write(str(msg) + "\n")
        sys.exit(2)
else:
    last_dir = recollect.get("playground", "last_used")
    if os.path.isdir(last_dir):
        try:
            os.chdir(last_dir)
        except OSError as msg:
            pass # open in current directory

try:
    main_window.MainWindow().show()
    Gtk.main()
except SystemExit as edata:
    raise edata # let the usual suspects handle this
except:
    dialogue.ask_for_bug_report(sys.exc_info())
    sys.exit(3)
